// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qpboxskxiqpbvpgncxnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwYm94c2t4aXFwYnZwZ25jeG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMDIwNDUsImV4cCI6MjA4OTY3ODA0NX0.32z-d-09DB3Yee36Dicbo_ZbsQmnjbFXrY87z3GuxE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);