// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oblzusunvgzfaoxkxfma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ibHp1c3Vudmd6ZmFveGt4Zm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMTIyMjgsImV4cCI6MjA4OTY4ODIyOH0.pPrJcKRSy_ez79EwLtox95PtudQBYWx1066dqz0zrWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);